version: '2'

services:
    xbox_controller:
        build:
            context: ../
            dockerfile: docker_scripts/hostDockerfile
        restart: always 
        command: ros2 launch autolaunch/launch/auto_launch.py
    ros_echo:
        image: osrf/ros:humble-desktop
        command: /bin/bash -c "ros2 topic list > /topic_list.txt && tail -f /dev/null" 
        depends_on:
          - xbox_controller
